[build]
  command = "npm run build"
  publish = "dist/pokemon-ssr/browser"

[context.production.environment]
  # Puedes usar una versión específica, o dejarlo sin versión para la más reciente
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  CHROME_BIN = "/usr/bin/google-chrome"
